apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  username: YXBwdXNlcm5hbWUK # base64 encoded string of ‘appusername’
  password: UGFzc3dvcmQxMjMK # base64 encoded string of ‘Password123’