apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: csi-secrets
    type: Opaque
    data: 
    - objectName: username
      key: username
    - objectName: password
      key: password
  parameters:
    usePodIdentity: "false"
    keyvaultName: "kvscrtbrownbag"
    objects:  |
      array:
        - |
          objectName: username
          objectType: secret
        - |
          objectName: password
          objectType: secret
    tenantId: "154ba0e0-f283-4b2d-b69f-dd599fe0e87e"  